# Generated by Django 4.2.6 on 2023-10-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_created_at_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Italian', 'Italian'), ('Japanese', 'Japanese')], default='en', max_length=20),
        ),
    ]
